services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: 7439466632
      POSTGRES_DB: insurance_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql+asyncpg://postgres:7439466632@db:5432/insurance_db

volumes:
  pgdata: